chore: Add RecommenderXBlock to the translation pipeline
openedx/openedx-translations pull request #140
Opened 2023-03-08 07:07 UTC by shadinaif

This PR needs https://github.com/openedx/RecommenderXBlock/pull/65 before it's merged.

Refs: FC-0012 OEP-58

2023-03-08 07:07 UTC, openedx-webhooks commented
Thanks for the pull request, @shadinaif!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-03-08 14:14 UTC, OmarIthawi requested changes
Thanks Shadi. Could you please use the _new_ standard `conf/locale` directory?

Also add to the github actions file: https://github.com/openedx/openedx-translations/blob/main/.github/workflows/extract-translation-source-files.yml#L41-L43

2023-03-08 14:14 UTC, OmarIthawi commented on transifex.yml
> +
```suggestion
  # RecommenderXBlock
  - filter_type: dir
    file_format: PO
    source_file_extension: po
    source_language: en
    source_file_dir: translations/RecommenderXBlock/recommender/conf/locale/en/
    translation_files_expression: 'translations/RecommenderXBlock/recommender/conf/locale/<lang>/'
```

2023-03-12 14:13 UTC, shadinaif commented on transifex.yml
> +
Done, thank you @OmarIthawi

2023-03-13 10:00 UTC, OmarIthawi commented
@shadinaif please add the entry to the github actions file: https://github.com/openedx/openedx-translations/blob/main/.github/workflows/extract-translation-source-files.yml#L41-L43

2023-03-13 10:16 UTC, OmarIthawi approved these changes

2023-03-23 17:59 UTC, brian-smith-tcril approved these changes
LGTM :shipit:

2023-03-23 18:19 UTC, brian-smith-tcril requested changes
I tested this by pushing the branch to my fork and it seems to be failing

https://github.com/brian-smith-tcril/openedx-translations/actions/runs/4503779916/jobs/7927421393

2023-03-30 06:28 UTC, shadinaif commented
@brian-smith-tcril it's because JS part is still not merged, I'll ping you again when it's good to go. Thank you!

2023-04-10 15:20 UTC, shadinaif commented
@brian-smith-tcril  This one will not fail after merging https://github.com/openedx/RecommenderXBlock/pull/68

2023-04-10 21:04 UTC, brian-smith-tcril approved these changes
[Tested on my fork](https://github.com/brian-smith-tcril/openedx-translations/actions/runs/4661000141/jobs/8249750693) and this is working now!

LGTM :shipit:

2023-04-10 21:04 UTC, merged