feat: Add credentials-themes to the translation pipeline
openedx/openedx-translations pull request #383
Opened 2023-06-09 14:51 UTC by shadinaif

feat: Add [credentials-themes](https://github.com/openedx/credentials-themes) to the translation pipeline

**IMPORTANT:** This PR needs https://github.com/openedx/credentials-themes/pull/613 before it's merged.

- [ ] Verified in a test PR in a forked repo: 

Refs:
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).
see details [here](https://github.com/openedx/xblock-submit-and-compare/pull/96)

2023-06-09 14:51 UTC, openedx-webhooks commented
Thanks for the pull request, @shadinaif!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2023-06-10 13:26 UTC, shadinaif commented
@OmarIthawi @brian-smith-tcril please review

2023-06-12 13:29 UTC, OmarIthawi requested changes
`credentials-theme` is neither and XBlock or Open edX plugin with `apps.py`, therefore it shouldn't have a link in the `edx-platform-links` directory.

There's a note saying:

```
          # Note: Add `module_name` for all edx-platform plugins and XBlocks such as DoneXBlock and completion, but not
          #       for micrsoervices and IDAs such as course-discovery and credentials.
```

It should add a link to the full document ( https://github.com/openedx/openedx-translations/tree/main/translations/edx-platform-links ) and updates `module_name` --> `python_module_name`.

2023-06-12 13:29 UTC, OmarIthawi commented on .github/workflows/extract-translation-source-files.yml
> +            python_module_name: edx_credentials_themes
```suggestion
          - repo_name: credentials-themes  # not an edx-platform plugin
```

2023-07-22 17:24 UTC, OmarIthawi commented
@shadinaif reminder for the review required changes.

2023-08-01 02:33 UTC, OmarIthawi commented
@shadinaif this seems to be a quick one to get it merged. Would you mind checking it out?

2023-09-21 09:24 UTC, shadinaif commented
Thank you @OmarIthawi , I also performed a new test, just in case

It's working fine https://github.com/Zeit-Labs/openedx-translations/pull/75/files#r1332758489

2023-10-18 06:53 UTC, OmarIthawi commented
I've converted to draft, to avoid accidental merge.

2023-10-23 18:36 UTC, OmarIthawi commented
@shadinaif the related https://github.com/openedx/credentials-themes/pull/613 PR has been merged. Please check this one and let me if we should merge it.

2023-10-25 20:35 UTC, brian-smith-tcril approved these changes

2023-10-25 20:37 UTC, merged

2023-10-25 20:37 UTC, openedx-webhooks commented
@shadinaif 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-translations&entry.867055334=https://github.com/openedx/openedx-translations/pull/383&entry.1484655318=https://github.com/shadinaif&entry.752974735=2023-06-09+14:51&entry.1917517419=2023-10-25+20:37&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->